# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_updete(object):
    def setupUi(self, updete):
        updete.setObjectName("updete")
        updete.resize(500, 300)
        self.widget = QtWidgets.QWidget(updete)
        self.widget.setGeometry(QtCore.QRect(0, 0, 500, 300))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 50, 150, 150))
        self.label.setStyleSheet("border-image: url(:/image/image/logo.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(460, 10, 25, 25))
        self.pushButton.setStyleSheet("border-image: url(:/ico/ico/close.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(250, 20, 130, 50))
        self.label_2.setStyleSheet("color: rgb(85, 85, 255);\n"
"font: 18pt \"华文行楷\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 210, 130, 50))
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 85, 255);\n"
"    font: 14pt \"华文行楷\";\n"
"    border-radius:20px;\n"
"}\n"
"#pushButton_2:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/ico/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(200, 80, 250, 200))
        self.label_3.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(240, 240, 240);\n"
"padding-left:10px;\n"
"font: 10pt \"宋体\";")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(updete)
        self.pushButton.clicked.connect(updete.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(updete)

    def retranslateUi(self, updete):
        _translate = QtCore.QCoreApplication.translate
        updete.setWindowTitle(_translate("updete", "update"))
        self.label_2.setText(_translate("updete", "发现新版本"))
        self.pushButton_2.setText(_translate("updete", "立即更新"))
        self.label_3.setText(_translate("updete", "1.添加新功能\n"
"2.下载速度优化\n"
"3.添加新平台"))
import resource_rc
