# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoCat(object):
    def setupUi(self, VideoCat):
        VideoCat.setObjectName("VideoCat")
        VideoCat.resize(1300, 800)
        self.widget = QtWidgets.QWidget(VideoCat)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1300, 800))
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 300, 800))
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 800))
        self.label.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"border-radius:30px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(40, 0, 200, 200))
        self.label_3.setStyleSheet("border-image: url(:/image/image/logo.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setGeometry(QtCore.QRect(50, 200, 200, 300))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget_4)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setStyleSheet("#pushButton{\n"
"    border:none;\n"
"    color: rgb(85, 85, 255);\n"
"    font: 18pt \"华文行楷\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}\n"
"#pushButton:hover{\n"
"    border:none;\n"
"    color: rgb(85, 85, 255);\n"
"    font: 18pt \"华文行楷\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}\n"
"#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"#pushButton:focus{\n"
"    border:none;\n"
"    color: rgb(85, 85, 255);\n"
"    font: 18pt \"华文行楷\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 18pt \"华文行楷\";\n"
"}\n"
"#pushButton_2:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"#pushButton_2:hover{\n"
"    border:none;\n"
"    color: rgb(85, 85, 255);\n"
"    font: 18pt \"华文行楷\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}\n"
"#pushButton_2:focus{\n"
"    border:none;\n"
"    color: rgb(85, 85, 255);\n"
"    font: 18pt \"华文行楷\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 18pt \"华文行楷\";\n"
"}\n"
"#pushButton_3:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"#pushButton_3:hover{\n"
"    border:none;\n"
"    color: rgb(85, 85, 255);\n"
"    font: 18pt \"华文行楷\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}\n"
"#pushButton_3:focus{\n"
"    border:none;\n"
"    color: rgb(85, 85, 255);\n"
"    font: 18pt \"华文行楷\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_4.setStyleSheet("#pushButton_4{\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 18pt \"华文行楷\";\n"
"}\n"
"#pushButton_4:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"#pushButton_4:hover{\n"
"    border:none;\n"
"    color: rgb(85, 85, 255);\n"
"    font: 18pt \"华文行楷\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}\n"
"#pushButton_4:focus{\n"
"    border:none;\n"
"    color: rgb(85, 85, 255);\n"
"    font: 18pt \"华文行楷\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_5.setStyleSheet("#pushButton_5{\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 18pt \"华文行楷\";\n"
"}\n"
"#pushButton_5:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"#pushButton_5:hover{\n"
"    border:none;\n"
"    color: rgb(85, 85, 255);\n"
"    font: 18pt \"华文行楷\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}\n"
"#pushButton_5:focus{\n"
"    border:none;\n"
"    color: rgb(85, 85, 255);\n"
"    font: 18pt \"华文行楷\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(250, 0, 1050, 800))
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1050, 800))
        self.label_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setGeometry(QtCore.QRect(960, 10, 72, 30))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_6.setStyleSheet("border-image: url(:/ico/ico/lower.png);")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_7.setStyleSheet("border-image: url(:/ico/ico/close.png);")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setGeometry(QtCore.QRect(100, 50, 900, 700))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget_6 = QtWidgets.QWidget(self.page)
        self.widget_6.setGeometry(QtCore.QRect(0, 0, 900, 700))
        self.widget_6.setObjectName("widget_6")
        self.widget_7 = QtWidgets.QWidget(self.widget_6)
        self.widget_7.setGeometry(QtCore.QRect(0, 0, 900, 50))
        self.widget_7.setObjectName("widget_7")
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        self.widget_8.setGeometry(QtCore.QRect(0, 0, 200, 50))
        self.widget_8.setObjectName("widget_8")
        self.label_4 = QtWidgets.QLabel(self.widget_8)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 100, 50))
        self.label_4.setStyleSheet("font: 18pt \"华文行楷\";")
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.widget_8)
        self.comboBox.setGeometry(QtCore.QRect(100, 5, 100, 40))
        self.comboBox.setStyleSheet("#comboBox {\n"
"    border-radius:10px;\n"
"    font: 16pt \"华文行楷\";\n"
"    border-color: rgb(85, 85, 255);\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"}\n"
"\n"
"#comboBox:editable {\n"
"    background: rgb(85, 85, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.widget_9 = QtWidgets.QWidget(self.widget_7)
        self.widget_9.setGeometry(QtCore.QRect(200, 0, 450, 50))
        self.widget_9.setObjectName("widget_9")
        self.label_5 = QtWidgets.QLabel(self.widget_9)
        self.label_5.setGeometry(QtCore.QRect(50, 0, 100, 50))
        self.label_5.setStyleSheet("font: 18pt \"华文行楷\";")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit.setGeometry(QtCore.QRect(150, 5, 300, 40))
        self.lineEdit.setStyleSheet("#lineEdit {\n"
"    font: 75 12pt \"Alimama ShuHeiTi\";\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: rgb(85, 85, 255);\n"
"    border-radius:10px\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.widget_10 = QtWidgets.QWidget(self.widget_7)
        self.widget_10.setGeometry(QtCore.QRect(650, 0, 250, 50))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_2.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_8.setStyleSheet("#pushButton_8{\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 15pt \"华文行楷\";\n"
"    background-color: rgb(85, 85, 255);\n"
"    border-radius:20px;\n"
"}\n"
"#pushButton_8:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_9.setStyleSheet("#pushButton_9{\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 15pt \"华文行楷\";\n"
"    background-color: rgb(85, 85, 255);\n"
"    border-radius:20px;\n"
"}\n"
"#pushButton_9:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_2.addWidget(self.pushButton_9)
        self.widget_11 = QtWidgets.QWidget(self.widget_6)
        self.widget_11.setGeometry(QtCore.QRect(0, 650, 900, 50))
        self.widget_11.setObjectName("widget_11")
        self.label_18 = QtWidgets.QLabel(self.widget_11)
        self.label_18.setGeometry(QtCore.QRect(0, 20, 60, 12))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.widget_11)
        self.label_19.setGeometry(QtCore.QRect(60, 20, 140, 12))
        self.label_19.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.widget_11)
        self.label_20.setGeometry(QtCore.QRect(200, 20, 60, 12))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.widget_11)
        self.label_21.setGeometry(QtCore.QRect(260, 20, 140, 12))
        self.label_21.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget_11)
        self.label_22.setGeometry(QtCore.QRect(400, 20, 60, 12))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.widget_11)
        self.label_23.setGeometry(QtCore.QRect(460, 20, 140, 12))
        self.label_23.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_23.setObjectName("label_23")
        self.widget_12 = QtWidgets.QWidget(self.widget_6)
        self.widget_12.setGeometry(QtCore.QRect(0, 50, 900, 50))
        self.widget_12.setObjectName("widget_12")
        self.label_6 = QtWidgets.QLabel(self.widget_12)
        self.label_6.setGeometry(QtCore.QRect(0, 20, 50, 12))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_12)
        self.label_7.setGeometry(QtCore.QRect(50, 20, 200, 12))
        self.label_7.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.label_16 = QtWidgets.QLabel(self.widget_12)
        self.label_16.setGeometry(QtCore.QRect(800, 20, 60, 12))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.widget_12)
        self.label_17.setGeometry(QtCore.QRect(860, 20, 40, 12))
        self.label_17.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_17.setObjectName("label_17")
        self.label_24 = QtWidgets.QLabel(self.widget_12)
        self.label_24.setGeometry(QtCore.QRect(250, 20, 60, 12))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.widget_12)
        self.label_25.setGeometry(QtCore.QRect(310, 20, 200, 12))
        self.label_25.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_25.setObjectName("label_25")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_6)
        self.tableWidget.setGeometry(QtCore.QRect(0, 100, 900, 550))
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.widget_19 = QtWidgets.QWidget(self.page_2)
        self.widget_19.setGeometry(QtCore.QRect(0, 100, 900, 150))
        self.widget_19.setObjectName("widget_19")
        self.label_40 = QtWidgets.QLabel(self.widget_19)
        self.label_40.setGeometry(QtCore.QRect(0, 0, 900, 150))
        self.label_40.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border-radius:20px;")
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.widget_19)
        self.label_41.setGeometry(QtCore.QRect(20, 20, 100, 50))
        self.label_41.setStyleSheet("font: 14pt \"华文行楷\";")
        self.label_41.setObjectName("label_41")
        self.pushButton_19 = QtWidgets.QPushButton(self.widget_19)
        self.pushButton_19.setGeometry(QtCore.QRect(820, 35, 35, 20))
        self.pushButton_19.setStyleSheet("border-image: url(:/ico/ico/open.png);")
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.widget_19)
        self.pushButton_20.setGeometry(QtCore.QRect(820, 35, 35, 20))
        self.pushButton_20.setStyleSheet("border-image: url(:/ico/ico/shut.png);")
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_42 = QtWidgets.QLabel(self.widget_19)
        self.label_42.setGeometry(QtCore.QRect(20, 70, 100, 50))
        self.label_42.setStyleSheet("font: 14pt \"华文行楷\";")
        self.label_42.setObjectName("label_42")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_19)
        self.lineEdit_6.setGeometry(QtCore.QRect(490, 80, 300, 30))
        self.lineEdit_6.setStyleSheet("#lineEdit_6 {\n"
"    font: 75 10pt \"Alimama ShuHeiTi\";\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: rgb(85, 85, 255);\n"
"    border-radius:10px\n"
"}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_21 = QtWidgets.QPushButton(self.widget_19)
        self.pushButton_21.setGeometry(QtCore.QRect(800, 82, 55, 25))
        self.pushButton_21.setStyleSheet("#pushButton_21{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(85, 85, 255);\n"
"    border-radius:10px;\n"
"}\n"
"#pushButton_21:pressed{\n"
"    padding-left:2.5px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_40.raise_()
        self.label_41.raise_()
        self.pushButton_20.raise_()
        self.label_42.raise_()
        self.lineEdit_6.raise_()
        self.pushButton_21.raise_()
        self.pushButton_19.raise_()
        self.label_43 = QtWidgets.QLabel(self.page_2)
        self.label_43.setGeometry(QtCore.QRect(0, 0, 60, 50))
        self.label_43.setStyleSheet("font: 22pt \"华文行楷\";")
        self.label_43.setObjectName("label_43")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_48 = QtWidgets.QLabel(self.page_3)
        self.label_48.setGeometry(QtCore.QRect(0, 50, 300, 40))
        self.label_48.setStyleSheet("font: 17pt \"华文行楷\";")
        self.label_48.setObjectName("label_48")
        self.widget_20 = QtWidgets.QWidget(self.page_3)
        self.widget_20.setGeometry(QtCore.QRect(100, 150, 700, 300))
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(100)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_46 = QtWidgets.QLabel(self.widget_20)
        self.label_46.setStyleSheet("border-image: url(:/image/image/wxPay.jpg);")
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_9.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(self.widget_20)
        self.label_47.setMinimumSize(QtCore.QSize(300, 300))
        self.label_47.setStyleSheet("border-image: url(:/image/image/aliPay.jpg);")
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_9.addWidget(self.label_47)
        self.label_49 = QtWidgets.QLabel(self.page_3)
        self.label_49.setGeometry(QtCore.QRect(0, 0, 60, 50))
        self.label_49.setStyleSheet("font: 22pt \"华文行楷\";")
        self.label_49.setObjectName("label_49")
        self.widget_21 = QtWidgets.QWidget(self.page_3)
        self.widget_21.setGeometry(QtCore.QRect(100, 450, 700, 30))
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(100)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_50 = QtWidgets.QLabel(self.widget_21)
        self.label_50.setStyleSheet("font: 18pt \"华文行楷\";")
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_10.addWidget(self.label_50, 0, QtCore.Qt.AlignHCenter)
        self.label_51 = QtWidgets.QLabel(self.widget_21)
        self.label_51.setStyleSheet("font: 18pt \"华文行楷\";")
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_10.addWidget(self.label_51, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_52 = QtWidgets.QLabel(self.page_4)
        self.label_52.setGeometry(QtCore.QRect(350, 50, 200, 200))
        self.label_52.setStyleSheet("border-image: url(:/image/image/logo.png);")
        self.label_52.setText("")
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.page_4)
        self.label_53.setGeometry(QtCore.QRect(0, 0, 60, 50))
        self.label_53.setStyleSheet("font: 22pt \"华文行楷\";")
        self.label_53.setObjectName("label_53")
        self.widget_23 = QtWidgets.QWidget(self.page_4)
        self.widget_23.setGeometry(QtCore.QRect(100, 300, 700, 50))
        self.widget_23.setObjectName("widget_23")
        self.label_59 = QtWidgets.QLabel(self.widget_23)
        self.label_59.setGeometry(QtCore.QRect(80, 0, 620, 40))
        self.label_59.setStyleSheet("font: 14pt \"新宋体\";")
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.widget_23)
        self.label_60.setGeometry(QtCore.QRect(0, 0, 80, 20))
        self.label_60.setStyleSheet("font: 16pt \"华文行楷\";")
        self.label_60.setObjectName("label_60")
        self.widget_22 = QtWidgets.QWidget(self.page_4)
        self.widget_22.setGeometry(QtCore.QRect(100, 350, 700, 150))
        self.widget_22.setObjectName("widget_22")
        self.label_61 = QtWidgets.QLabel(self.widget_22)
        self.label_61.setGeometry(QtCore.QRect(0, 0, 700, 120))
        self.label_61.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border-radius:20px;")
        self.label_61.setText("")
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.widget_22)
        self.label_62.setGeometry(QtCore.QRect(10, 70, 100, 30))
        self.label_62.setStyleSheet("font: 14pt \"华文行楷\";")
        self.label_62.setObjectName("label_62")
        self.pushButton_33 = QtWidgets.QPushButton(self.widget_22)
        self.pushButton_33.setGeometry(QtCore.QRect(600, 10, 70, 25))
        self.pushButton_33.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 85, 255);\n"
"border-radius:10px;")
        self.pushButton_33.setObjectName("pushButton_33")
        self.label_63 = QtWidgets.QLabel(self.widget_22)
        self.label_63.setGeometry(QtCore.QRect(10, 10, 100, 50))
        self.label_63.setStyleSheet("font: 14pt \"华文行楷\";")
        self.label_63.setObjectName("label_63")
        self.pushButton_34 = QtWidgets.QPushButton(self.widget_22)
        self.pushButton_34.setGeometry(QtCore.QRect(600, 70, 70, 25))
        self.pushButton_34.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 85, 255);\n"
"border-radius:10px;")
        self.pushButton_34.setObjectName("pushButton_34")
        self.label_64 = QtWidgets.QLabel(self.page_4)
        self.label_64.setGeometry(QtCore.QRect(400, 230, 125, 50))
        self.label_64.setStyleSheet("font: 20pt \"方正粗黑宋简体\";")
        self.label_64.setObjectName("label_64")
        self.stackedWidget.addWidget(self.page_4)
        self.widget_3.raise_()
        self.widget_2.raise_()

        self.retranslateUi(VideoCat)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_6.clicked.connect(VideoCat.showMinimized) # type: ignore
        self.pushButton_7.clicked.connect(VideoCat.close) # type: ignore
        self.pushButton_19.clicked.connect(self.pushButton_20.show) # type: ignore
        self.pushButton_20.clicked.connect(self.pushButton_19.show) # type: ignore
        self.pushButton_19.clicked.connect(self.pushButton_19.hide) # type: ignore
        self.pushButton_20.clicked.connect(self.pushButton_20.hide) # type: ignore
        self.pushButton_5.clicked.connect(VideoCat.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(VideoCat)

    def retranslateUi(self, VideoCat):
        _translate = QtCore.QCoreApplication.translate
        VideoCat.setWindowTitle(_translate("VideoCat", "VideoCat"))
        self.pushButton.setText(_translate("VideoCat", "首页"))
        self.pushButton_2.setText(_translate("VideoCat", "设置"))
        self.pushButton_3.setText(_translate("VideoCat", "打赏"))
        self.pushButton_4.setText(_translate("VideoCat", "关于"))
        self.pushButton_5.setText(_translate("VideoCat", "退出"))
        self.label_4.setText(_translate("VideoCat", "选择类型"))
        self.comboBox.setItemText(0, _translate("VideoCat", "主页"))
        self.comboBox.setItemText(1, _translate("VideoCat", "喜欢"))
        self.comboBox.setItemText(2, _translate("VideoCat", "合集"))
        self.label_5.setText(_translate("VideoCat", "分享链接"))
        self.lineEdit.setPlaceholderText(_translate("VideoCat", "请输入分享链接"))
        self.pushButton_8.setText(_translate("VideoCat", "获取数据"))
        self.pushButton_9.setText(_translate("VideoCat", "全部下载"))
        self.label_18.setText(_translate("VideoCat", "视频数量："))
        self.label_19.setText(_translate("VideoCat", "0"))
        self.label_20.setText(_translate("VideoCat", "下载成功："))
        self.label_21.setText(_translate("VideoCat", "0"))
        self.label_22.setText(_translate("VideoCat", "下载失败："))
        self.label_23.setText(_translate("VideoCat", "0"))
        self.label_6.setText(_translate("VideoCat", "用户名："))
        self.label_7.setText(_translate("VideoCat", "未获取"))
        self.label_16.setText(_translate("VideoCat", "视频类型："))
        self.label_17.setText(_translate("VideoCat", "未获取"))
        self.label_24.setText(_translate("VideoCat", "合集名称："))
        self.label_25.setText(_translate("VideoCat", "未获取"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("VideoCat", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("VideoCat", "标题"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("VideoCat", "链接"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("VideoCat", "状态"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("VideoCat", "操作"))
        self.label_41.setText(_translate("VideoCat", "输出日志"))
        self.label_42.setText(_translate("VideoCat", "保存路径"))
        self.lineEdit_6.setPlaceholderText(_translate("VideoCat", "默认放在软件下Download目录"))
        self.pushButton_21.setText(_translate("VideoCat", "更改"))
        self.label_43.setText(_translate("VideoCat", "设置"))
        self.label_48.setText(_translate("VideoCat", "你的支持就是作者最大的动力"))
        self.label_49.setText(_translate("VideoCat", "赞助"))
        self.label_50.setText(_translate("VideoCat", "微信"))
        self.label_51.setText(_translate("VideoCat", "支付宝"))
        self.label_53.setText(_translate("VideoCat", "关于"))
        self.label_59.setText(_translate("VideoCat", "VideoCat(视频猫) 是一款专注于做视频爬虫的软件，目前仅支持抖音，\n"
"后续将会不断进行更新和优化，感谢大家使用。"))
        self.label_60.setText(_translate("VideoCat", "介绍："))
        self.label_62.setText(_translate("VideoCat", "开发者"))
        self.pushButton_33.setText(_translate("VideoCat", "v 1.0.2"))
        self.label_63.setText(_translate("VideoCat", "当前版本"))
        self.pushButton_34.setText(_translate("VideoCat", "Comfort"))
        self.label_64.setText(_translate("VideoCat", "VideoCat"))
import resource_rc
